generator: # in %
  basic:
    "ancient_debris": 0.01
    "diamond_ore": 0.5
    "gold_ore": 1
    "iron_ore": 2
    "coal_ore": 5
    "redstone_ore": 2
    "lapis_ore": 2
    "cobbled_deepslate": 10
    "diorite": 3
    "netherrack": 3
    "andesite": 3
    "granite": 3
  upgrades:
    "netherite_block": "ancient_debris"
    "gold_block": "gold_ore"
    "iron_block": "iron_ore"
    "lapis_block": "lapis_ore"
    "coal_block": "coal_ore"
    "redstone_block": "redstone_ore"
    "polished_deepslate": "cobbled_deepslate"
    "diamond_block": "diamond_ore"
    "polished_diorite": "diorite"
    "nether_brick": "netherrack"
    "polished_granite": "granite"
    "polished_andesite": "andesite"
  upgraded:
    "ancient_debris": 0.05
    "diamond_ore": 1
    "gold_ore": 3
    "iron_ore": 5
    "coal_ore": 8
    "redstone_ore": 5
    "lapis_ore": 4
    "cobbled_deepslate": 20
    "diorite": 20
    "netherrack": 20
    "andesite": 20
    "granite": 20
