name: MultiSkyblockUtils
version: 1.0.0
api-version: 1.20
main: lu.kbra.multi_skyblock_utils.MultiSkyblockUtils
author: UnKabaraQuiDev@github.com
# depend: [ProtocolLib]
commands:
  island:
    name: "island"
    aliases: ["is"]
  clearconfig:
    name: "clearconfig"
    permission: op
  reloadconfig:
    name: "reloadconfig"
    permission: op
  configisland:
    name: "configisland"
    aliases: ["cis"]
  confine:
    name: "confine"
    permission: op
  home:
    name: "home"
    aliases: ["h"]
  homes:
    name: "homes"
    aliases: ["hs"]
  sethome:
    name: "sethome"
    aliases: ["sh"]
  delhome:
    name: "delhome"
    aliases: ["dh"]