name: MultiSkyblockUtils
version: 1.0.0
api-version: 1.20
main: lu.kbra.multi_skyblock_utils.MultiSkyblockUtils
author: UnKabaraQuiDev@github.com
commands:
  island:
    name: "island"
    aliases: ["is"]
  clearconfig:
    name: "clearconfig"
